### ISSUE TITLE
Not able to install via conda

### ISSUE THREAD

**Issue by kiranpatil222** [MDU-PHL/meningotype#45]
Hi,

I could install other conda apps, but for menigotype its getting stuck at resolving environments

**Comment by omegatro** [comment]
**Hello!**

Here’s a working set of dependencies for `meningotype v0.8.5`:

```yaml
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - meningotype=0.8.5
  - biopython
  - blast=2.13.0
  - mlst
  - ispcr
```
You can save this to a .yaml file and create the environment using: `conda env create -f <path_to_yaml>`
Hope this helps!
